#!/bin/sh

if [ "$PARROT_ENABLE" = 1 ]; then
    echo 'Starting HBlink with Parrot.....'
    python bridge.py -c hblink.cfg -r rules.py &
    python playback.py -c playback.cfg
else
    echo 'Starting HBlink.....'
    exec python bridge.py -c hblink.cfg -r rules.py
fi
